In [4]:
import numpy as np
import random

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1.1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).

   2.1 Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [53]:
vector_random_uniform = np.round([random.uniform(0, 1) for _ in range(10)], 2)
print('Генерація випадкових чисел з модулем random.uniform:', vector_random_uniform)

print('\n')

vector_random_rand = np.round(np.random.rand(10), 2)
print('Створення вектора з допомогою метода np.random.rand: ', vector_random_rand)

matrix = np.array([
            [11, 14, 17],
            [20, 23, 26],
            [29, 32, 35]
        ])

print('\n')

print('Матриця:', matrix)

print('\n')


Генерація випадкових чисел з модулем random.uniform: [0.72 0.38 0.01 0.49 0.71 0.94 0.   0.76 0.27 0.99]


Створення вектора з допомогою метода np.random.rand:  [0.67 0.69 0.19 0.67 0.78 0.24 0.76 0.79 0.72 0.71]


Матриця: [[11 14 17]
 [20 23 26]
 [29 32 35]]





### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [55]:
vector_random_rand_plus_10 = np.round(10 + vector_random_rand, 2)

print('Вектор + 10:', vector_random_rand_plus_10)
print('\n')

matrix_mult_2 = matrix * 2

print('Матриця помножена на 2:', matrix_mult_2)
print('\n')

vector_squared = vector_random_rand ** 2

print('Вектор в квадраті:', vector_squared)
print('\n')

Вектор + 10: [10.67 10.69 10.19 10.67 10.78 10.24 10.76 10.79 10.72 10.71]


Матриця помножена на 2: [[22 28 34]
 [40 46 52]
 [58 64 70]]


Вектор в квадраті: [0.4489 0.4761 0.0361 0.4489 0.6084 0.0576 0.5776 0.6241 0.5184 0.5041]





### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [56]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

print(A)
print('\n')
print(B)
print('\n')
print(C)
print('\n')
print(D)
print('\n')

[[0.18 0.53]
 [0.75 0.47]
 [0.35 0.21]]


[[0.17 0.58 0.75]
 [0.38 0.11 0.15]]


[[0]
 [1]]


[[0 1]
 [1 0]]




In [57]:
result_matrix = np.dot(A[:2], B[:, :2])
print('Множення матриць:', result_matrix)
print('\n')

result_matrix_C = np.dot(result_matrix, C)
print('Множення матриці на вектор 1:', result_matrix_C)
print('\n')

result_matrix_D = np.dot(result_matrix, D)
print('Множення матриці на вектор 2:', result_matrix_D)
print('\n')

Множення матриць: [[0.232  0.1627]
 [0.3061 0.4867]]


Множення матриці на вектор 1: [[0.1627]
 [0.4867]]


Множення матриці на вектор 2: [[0.1627 0.232 ]
 [0.4867 0.3061]]





### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [64]:
result_matrix_T = result_matrix.T
print('Транспонування матриці на вектор result_matrix:', result_matrix_T)
print('\n')

vector_random_uniform_T = vector_random_uniform.T
print('Оригінальний вектор:', vector_random_uniform, vector_random_uniform.shape)
print('Транспонований вектор result_matrix:', vector_random_uniform_T, vector_random_uniform_T.shape)
print('Після транспонування вектор не змінився.')
print('\n')

column_vector = np.expand_dims(vector_random_uniform, axis=1)
print('Оригінальний вектор:', vector_random_uniform, vector_random_uniform.shape)
print('Новий вектор:', column_vector, column_vector.shape)
print('\n')

column_vector_T = column_vector.T
print('Оригінальний вектор:', column_vector, column_vector.shape)
print('Трансопонований вектор:', column_vector_T, column_vector_T.shape)
print('\n')


Транспонування матриці на вектор result_matrix: [[0.232  0.3061]
 [0.1627 0.4867]]


Оригінальний вектор: [0.72 0.38 0.01 0.49 0.71 0.94 0.   0.76 0.27 0.99] (10,)
Транспонований вектор result_matrix: [0.72 0.38 0.01 0.49 0.71 0.94 0.   0.76 0.27 0.99] (10,)
Після транспонування вектор не змінився.


Оригінальний вектор: [0.72 0.38 0.01 0.49 0.71 0.94 0.   0.76 0.27 0.99] (10,)
Новий вектор: [[0.72]
 [0.38]
 [0.01]
 [0.49]
 [0.71]
 [0.94]
 [0.  ]
 [0.76]
 [0.27]
 [0.99]] (10, 1)


Оригінальний вектор: [[0.72]
 [0.38]
 [0.01]
 [0.49]
 [0.71]
 [0.94]
 [0.  ]
 [0.76]
 [0.27]
 [0.99]] (10, 1)
Трансопонований вектор: [[0.72 0.38 0.01 0.49 0.71 0.94 0.   0.76 0.27 0.99]] (1, 10)


